## Based on rocker/hadleyverse maintained by Carl Boettiger and Dirk Eddelbuettel
FROM taptao/shiny

# install R packages
Run Rscript -e 'install.packages(pkgs= "plyr", dependencies = TRUE)'
Run Rscript -e 'install.packages(pkgs= "maps", dependencies = TRUE)'
Run Rscript -e 'install.packages(pkgs= "mapproj", dependencies = TRUE)'
